### ISSUE TITLE
Error running docker-compose on the latest code

### ISSUE THREAD

**Issue by psiphi75** [brooks-builds/full-stack-todo-rust-course#10]
I'm following your Yew introduction, specifically the "Introducing the Project - Introduction to Yew" video and have just cloned this repository to follow along.

However, the following command fails with the shown error message:

```sh
docker-compose --profile js-vue up
ERROR: build path /[MY PATH]/full-stack-todo-rust-course/backend/rust/learning_axum either does not exist, is not accessible, or is not a valid URL.
```

I reverted to the `c0ccf9` commit and it works fine.

By the way, thanks for all your videos, they make learning Yew easier.

**Comment by BrooksPatton** [comment]
I bet that's due to the new Axum course section of the docker compose file not having a profile. Thanks for the catch. I'll fix that next stream and get it tested and merged.

**Comment by BrooksPatton** [comment]
I fixed the docker compose file and it doesn't cause an error when running the `docker-compose --profile js-vue up ` command anymore
