### ISSUE TITLE
Use State instead of Extension

### ISSUE THREAD

**Issue by romanstingler** [brooks-builds/full-stack-todo-rust-course#12]
https://github.com/brooks-builds/full-stack-todo-rust-course/blob/bcd6ea71e4bf52af46d2b919cf35c2a78a7c1c7c/backend/rust/axum/lessons/data/src/routes/get_tasks.rs#L51

probably you missed this line here

**Comment by BrooksPatton** [comment]
I checked the main branch, and it seems that I have that line so I'm guessing that I added it in another lesson? I can't remember exactly when.

But this is exactly what is needed in the branch you're referencing!
