### ISSUE TITLE
Incorrect Video URL in README.md

### ISSUE THREAD

**Issue by DavidAChris** [brooks-builds/full-stack-todo-rust-course#15]
In the following sections these two topics have the same youtube url.
styling struct components || https://youtu.be/KC7HCxr6OCE
&
struct properties || https://youtu.be/KC7HCxr6OCE

struct properties should go to https://youtu.be/qIIWv9oB_hU

**Comment by BrooksPatton** [comment]
Thanks! I set the struct properties video to be the correct one.
